### ISSUE TITLE
パーツをマウスドラッグで回転させると、パーツが見えなくなる

### ISSUE THREAD

**Issue by hosokawa-tatsuhiro** [IRSL-tut/robot_assembler_plugin#115]
alt+shiftを押しながらパーツ上でマウスを動かすと、パーツが見えなくなる。Itemsにはパーツ名がある。カーソルをゆっくり動かしても消えるため、カーソルの移動速度は関係ないと思われる。

**Comment by YoheiKakiuchi** [comment]
@hosokawa-tatsuhiro 修正されたと思います。確認してください。
