### ISSUE TITLE
設置の仕方で回転方向が異なる

### ISSUE THREAD

**Issue by Hiroaki-Masuzawa** [IRSL-tut/robot_assembler_plugin#12]
同じ角度を指定していても，逆方向に回転する．
おそらく #7 で認識されていなかった関節なので，そのあたりが関連しそう．
![20220902](https://user-images.githubusercontent.com/84704736/188077100-b719afdf-2e28-4855-8e8e-2e1b6219576e.png)

**Comment by YoheiKakiuchi** [comment]
.bodyに変換する時、関節位置が同じで、駆動の親子関係が逆になっているので、
逆変換にする必要がある気がしてきました（単軸だと逆方向に動かす）

**Comment by YoheiKakiuchi** [comment]
とりあえず、#7 で議論した関節について、軸の向きを反転させています。
まだ定義されていない複合関節以外は、想定通りの動きをするかと思います。
https://github.com/IRSL-tut/robot_assembler_plugin/pull/15
