### ISSUE TITLE
Copy paste robot parts

### ISSUE THREAD

**Issue by CoffMakesThings** [IRSL-tut/robot_assembler_plugin#27]
![image](https://user-images.githubusercontent.com/82292207/207790414-602ca961-3b17-424b-b0f9-9194185981c7.png)

I made half a robot. I want to copy and paste it. Is it possible?

**Comment by YoheiKakiuchi** [comment]
You can load .robasm file.
So, you can handle the other one if you save it and load saved .roboasm file.
Then, connect two robots.

**Comment by CoffMakesThings** [comment]
That works, thank you!
