### ISSUE TITLE
Saving history not possible after loading a roboasm twice

### ISSUE THREAD

**Issue by CoffMakesThings** [IRSL-tut/robot_assembler_plugin#28]
To reproduce the error, load the same roboasm file twice, then try to save history.

[void cnoid::AssemblerManager::updateRobots()] lst : 2
[void cnoid::AssemblerManager::updateRobots()] robot_list : 2
[void cnoid::AssemblerManager::com_save_history()] lst : 2
[void cnoid::AssemblerManager::com_save_history()] AssemblerItem more than 1

**Comment by YoheiKakiuchi** [comment]
I have an idea why that happens.

Copy "halfrobot.roboasm" as "halfrobot_copied.roboasm".
(Copy the original file as another name )

Open halfrobot_copied.roboasm by an editor.
You can see a description like 'parts-name: vehicle-base-pp_193_0'
The meaning of 'vehicle-base-pp_193_0' is '<parts-name>_<magic-number>_<counter>'.
The same part name must not be in two files.
So, you should replace <magic-number> with another string.
Then, you can open "halfrobot.roboasm" and add "halfrobot_copied.roboasm".

**Comment by CoffMakesThings** [comment]
Loading two copies instead of one copy twice fixes the problem.
