### ISSUE TITLE
各パーツの"class”と"description"をconfigファイルに追加する

### ISSUE THREAD

**Issue by tomosii** [IRSL-tut/robot_assembler_plugin#40]
irsl_assembler_config.yaml 内のそれぞれのパーツに対して、`class:`と`description:`を記載する。

- `class`
GUI上のボタンなどに表示されるuser-friendlyなパーツ名。

- `description` (未実装) 
パーツの説明。
マウスをホバーした時に表示させる予定。

**Comment by tomosii** [comment]
タブ名やclass名、descriptionのイメージです。
修正案などあればお願いいたします。

## Servo Parts (X-series)

### Dynamixel XL-430
Servomotor

### FR12-S101
Vertical side frame for X-series servomotor

### FR12-S102
Horizontal side frame for X-series servomotor

### FR12-S102 (P)
Horizontal side frame with LEGO plugs for X-series servomotor 

### FR12-S102 (S)
Horizontal side frame with LEGO sockets for X-series servomotor 

### FR12-H101 (P)
Small-sized hinge frame with LEGO plugs for X-series servomotor 

### FR12-H101 (S)
Small-sized hinge frame with LEGO sockets for X-series servomotor 

### FR12-H103 (P)
Large-sized hinge frame with LEGO plugs for X-series servomotor

### FR12-H103 (S)
Large-sized hinge frame  with LEGO sockets for X-series servomotor

### Bottom mount (S)
Bottom mount with LEGO sockets for X-series servomotor

### Omni shaft
Omni wheel shaft for X-series servomotor.

**Comment by YoheiKakiuchi** [comment]
説明はそれでいいかと思いますが、
名前は ```FR12-S101``` のような暗号的な名前じゃない方が良いように思います。

roboasmファイルが読みにくくなるという弊害はあるだろうか？

**Comment by tomosii** [comment]
修正いたしました。


<details>

<summary>
Servo Parts (X-series)
</summary>

### Dynamixel XL-430
Servomotor

### Vertical side frame
Vertical side frame for X-series servomotor

### Horizontal side frame 
Horizontal side frame for X-series servomotor

### Horizontal side frame (Plug)
Horizontal side frame with LEGO plugs for X-series servomotor 

### Horizontal side frame (Socket)
Horizontal side frame with LEGO sockets for X-series servomotor 

### Short hinge frame (Plug) 
Short hinge frame with LEGO plugs for X-series servomotor 

### Short hinge frame (Socket) 
Short hinge frame with LEGO sockets for X-series servomotor 

### Long hinge frame (Plug)
Long hinge frame with LEGO plugs for X-series servomotor

### Long hinge frame (Socket)
Long hinge frame  with LEGO sockets for X-series servomotor

### Bottom mount (Socket)
Bottom mount with LEGO sockets for X-series servomotor

### Omni shaft
Omni wheel shaft for X-series servomotor.

</details>

**Comment by YoheiKakiuchi** [comment]
あと、omni shaft -> wheel shaft とかかなと思います。

**Comment by tomosii** [comment]
見た目はこのような感じになります。

![Screenshot from 2023-02-07 16-57-37](https://user-images.githubusercontent.com/42999452/217185494-01a25d84-f3fd-4861-af1a-cc77c2a6f6a9.png)

**Comment by tomosii** [comment]
`servo_part_ax_series` 以外は一通り名前を決めました。

## Main Blocks

### Brick (2 x 2)
LEGO brick (2 x 2)

### Brick (2 x 3)
LEGO brick (2 x 3)


## Main Plates

### Plate (2 x 2)
LEGO plate (2 x 2)

### Plate (2 x 3)
LEGO plate (2 x 3)


## Special Parts

### Corner bracket (2 x 2)
LEGO corner bracket (2 x 2)

### Double-sided socket plate (2 x 2)
Plate with LEGO sockets on both sides (2 x 2)


## Vehicle Parts

### Base plate (deprecated)
This part is deprecated. Use "Base plate" instead.

### Base plate (deprecated)
This part is deprecated. Use "Base plate" instead.

### Base plate
Base plate for vehicles with LEGO plugs on both sides

### Omni wheel
Omni-directional wheel



## Sensor Parts
### Sensor mount (Socket)
Sensor mount with LEGO sockets for M5Stack sensors

### Ultrasonic sensor
M5Stack ultrasonic sensor

### TOF sensor
M5Stack time-of-flight sensor




## Servo Parts (X-series)

### Dynamixel XL-430
Servomotor

### Vertical side frame
Vertical side frame for X-series servomotor

### Horizontal side frame
Horizontal side frame for X-series servomotor

### Horizontal side frame (Plug)
Horizontal side frame with LEGO plugs for X-series servomotor 

### Horizontal side frame (Socket)
Horizontal side frame with LEGO sockets for X-series servomotor 

### Short hinge frame (Plug)
Short hinge frame with LEGO plugs for X-series servomotor 

### Short hinge frame (Socket)
Short hinge frame with LEGO sockets for X-series servomotor 

### Long hinge frame (Plug)
Long hinge frame with LEGO plugs for X-series servomotor

### Long hinge frame (Socket)
Long hinge frame  with LEGO sockets for X-series servomotor

### Back side frame (Socket)
Back side frame with LEGO sockets for X-series servomotor

### Wheel shaft
Omni wheel shaft for X-series servomotor.

**Comment by tomosii** [comment]
各パーツのconfigの中に `print-file:` というフィールドを新たに設定し、STLファイルとの対応がわかるようにファイル名を記載しておきたいと思います。

**Comment by YoheiKakiuchi** [comment]
表示されるファイルと3Dプリントのファイルが違うことあるんだっけ？

**Comment by Hiroaki-Masuzawa** [comment]
@YoheiKakiuchi 

> 表示されるファイルと3Dプリントのファイルが違うことあるんだっけ？

もともと"m"単位のファイルで構成されていたため，robot-assemblerで表示用のSTLファイルはm単位のものを利用していました．現在ではscaleパラメータが使用可能となっているため，特に分ける意味はなくなっています．

**Comment by tomosii** [comment]
YAMLのconfigからMarkdown形式のパーツ一覧表を出力するスクリプトを作りました。

出力されるファイル:
https://github.com/lighthouse117/robot_assembler_plugin/blob/b4e0320b1b609e5bb5501e29cc19acba894d090d/docs/parts_list.md

使用方法:
`python tools/parts_list_generator.py config/irsl/irsl_assembler_config.yaml`

**Comment by tomosii** [comment]
@YoheiKakiuchi 
meshesフォルダにあるSTLファイルをmm単位のものへ移行したほうがよろしいでしょうか？
mm単位に統一すれば、`print-file:`は必要なくなるかと思います。

**Comment by Hiroaki-Masuzawa** [comment]
現状blockとplateについてはrobot-assembler上ではstlを用いていないので，別途それらのパーツを用意しないのであれば`print-file:`は必要かと思います．そのため，以下のような感じに整理していくのがよいかと思います．

- 描画用にSTLファイルを用いる場合はmm単位のものを用いる．
- 都合mm単位のSTLファイルを用意できない，もしくは，robot-assemblerの描画にSTLを用いていない場合は`print-file:`に対象のファイルを記述する．

**Comment by tomosii** [comment]
VSCodeの`settings.json` で以下のようにYAMLファイルの自動整形をオフにしました。

```json
"[yaml]": {
    "editor.formatOnSave": false
}
```

**Comment by tomosii** [comment]
#49 のconnecting-points名の変更に合わせて、configのclass名もVertical, Horizontal → A,B,Cへ変更したいと思います。
