### ISSUE TITLE
assemblerでbodyファイルを保存した後choreonoidで読み込んだ時にメッシュとジョイントが反映されていない

### ISSUE THREAD

**Issue by Hiroaki-Masuzawa** [IRSL-tut/robot_assembler_plugin#5]
#3 で追加したax-12aを用いて組み立てbodyファイルに保存した後，choreonoidで読み込むとメッシュが表示されない．
また，Link等のプロパティも表示されない．(こちらは設定ファイルのミス？)

**Comment by YoheiKakiuchi** [comment]
番号つけてコミットしたら自動的に閉じてしまいましたが、メッシュは以下で修正されたと思います。
https://github.com/IRSL-tut/robot_assembler_plugin/commit/7bfd146268bea58294a7a0f89ce2b31c15726b5a

joint等については、ホーンに何か取り付けないとjointにならないので、attachの必要はあります。
また、bodyファイルのデバッグは、現状では、assembler.cnoidを使わない状態で行うのがよいです。
