### ISSUE TITLE
Configを独立させる

### ISSUE THREAD

**Issue by YoheiKakiuchi** [IRSL-tut/robot_assembler_plugin#60]
サンプル(kxr)を残してconfigを別のレポジトリで管理する

**Comment by Hiroaki-Masuzawa** [comment]
@YoheiKakiuchi 
[サンプル](https://github.com/Hiroaki-Masuzawa/config_repo_test)を作ってみました．
現状のconfigの中身をコピーして作成し，configファイルが読み込めるかのテストまで作成しております．
イメージあっておりますか？

**Comment by YoheiKakiuchi** [comment]
テストの書き方はどうしようかなというところはあるけれど、そんな感じです。

ディレクトリ名をどうするか考えたいけど、sampleを追加。

こちらは微妙だけども、 .cnoid ファイルも 追加かな。

あと、分離のタイミングで XL430を使う系列とAX12を使うの系列を 分離させたい。

**Comment by YoheiKakiuchi** [comment]
@Hiroaki-Masuzawa 

https://github.com/IRSL-tut/robot_assembler_config_IRSL に
分離したconfigのレポジトリを作りました。


> 分離のタイミングで XL430を使う系列とAX12を使うの系列を 分離させたい。

こちらは現状やっていない

AXの系列のみに必要なものをパネルに出なくするだけで良いように思う


> こちらは微妙だけども、 .cnoid ファイルも 追加かな。

.cnoidはこちらには追加しないようにする


- 今後の対応

robot_assembler_plugin/config/irsl => 消す

robot_assembler_plugin/sample => 消す

https://github.com/IRSL-tut/robot_assembler_config_IRSL を share/choreonoid-1.8/robot_assembler/irsl へインストール

これで同じ動作になるはず


- test

robot_assembler_pluginでバイナリ(or python)を作ってそれを呼ぶ

**Comment by Hiroaki-Masuzawa** [comment]
分離先のconfigで元のsampleデータ読み込めたので分離して問題なさそうです．

**Comment by YoheiKakiuchi** [comment]
dockerの方マージされたので現在のビルド
https://github.com/IRSL-tut/irsl_docker/actions/runs/4827996776
が終わったらirslのconfigは https://github.com/IRSL-tut/robot_assembler_config_IRSL に切り替わります。

https://github.com/IRSL-tut/irsl_docker/pull/9

**Comment by YoheiKakiuchi** [comment]
移動完了
https://github.com/IRSL-tut/robot_assembler_plugin/pull/90
