### ISSUE TITLE
駆動ジョイントが１か所認識されない

### ISSUE THREAD

**Issue by Hiroaki-Masuzawa** [IRSL-tut/robot_assembler_plugin#7]
組み立てた後，bodyファイルを読み込んだ時に１か所ジョイントが認識されない．

その時のbodyとroboasmファイルを以下に添付．
[data.zip](https://github.com/IRSL-tut/robot_assembler_plugin/files/9442871/data.zip)

**Comment by YoheiKakiuchi** [comment]
以下で修正されたかと思います。
https://github.com/IRSL-tut/robot_assembler_plugin/commit/94a2f58fd7569ca7d9293cada47676b624ac76aa

想定していた通りで、ConnectingPointの親子関係でActuatorが親にも子にもなり得る想定が抜けていました。

**Comment by Hiroaki-Masuzawa** [comment]
https://github.com/IRSL-tut/robot_assembler_plugin/blob/0b02de8833cd02384fb64773aadcae039c084ae1/src/RobotAssemblerBody.cpp#L60

上記 traverseSGが定義されていないので，コンパイルができずdocker buildができなかったです．
それを回避すれば関節が認識するところまで確認しました．
(今までなんでコンパイルできていたのでしょうか．．．．)

**Comment by YoheiKakiuchi** [comment]
手元にしかないデバッグ関数が紛れ込みました。
修正されているかと思います。
